# Server configurations
server:
  host: "localhost"
  port: 8803
  session_key: "1234567890"

# Database credentials
database:
  user: "admin"
  pass: "1234567890"
  file: "db.db"

# Website settings
frontend:
  admin: "admin"
  pass: "1234567890"
  site_name: "The Branch · Dunedin"
